# Generated by Django 3.1.2 on 2021-01-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tgenre',
            fields=[
                ('genreid', models.IntegerField(primary_key=True, serialize=False)),
                ('genrename', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'tgenre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('tourid', models.IntegerField(db_column='tourId', primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
                ('town', models.CharField(blank=True, max_length=20, null=True)),
                ('tourname', models.CharField(blank=True, max_length=40, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('score', models.CharField(blank=True, max_length=20, null=True)),
                ('tscore', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'travel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Treview',
            fields=[
                ('treviewno', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'treview',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tuser',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=10, null=True)),
                ('user_pwd', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'tuser',
                'managed': False,
            },
        ),
    ]
